name: update-algolia

on:
  schedule:
    - cron: '* */6 * * *'
jobs:
  build:
    name: Algolia Update
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update Algolia
        run: update-algolia.sh
